language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  matrix:
    - DJANGO='>=1.8, <1.9'
    - DJANGO='>=1.9, <1.10'
    - DJANGO='>=1.10, <1.11'
    - DJANGO='>=1.11, < 1.12'

install:
  - pip install --upgrade pip
  - pip install "django $DJANGO"
  - pip install -r requirements-test.txt

script: pytest create_admin
